
# Alpha diversity

## microbiota

```{r load_data_alpha}
load("data/data.Rdata")
treatment_colors <- c("#f56042","#429ef5", "#42f58d", "#b142f5")
sample_metadata$broad_environment <- factor(sample_metadata$broad_environment, levels=c("1000198 - Mixed forest", "1000221 - Temperate woodland", "1000218 - Xeric shrubland", "1000245 - Cropland"))
```

### Hill numbers
Richness of microbiotic species in samples
```{r alpha_div, comment="", message=FALSE, warning=FALSE}
# Calculate Hill numbers
richness <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 0) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(richness = 1) %>%
  rownames_to_column(var = "sample")

neutral <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(neutral = 1) %>%
  rownames_to_column(var = "sample")

phylogenetic <- genome_counts_filt %>%
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, tree = genome_tree) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(phylogenetic = 1) %>%
  rownames_to_column(var = "sample")

# Aggregate basal GIFT into elements
dist <- genome_gifts %>%
  to.elements(., GIFT_db) %>%
  traits2dist(., method = "gower")

functional <- genome_counts_filt %>%
  filter(genome %in% rownames(dist)) %>% 
  column_to_rownames(var = "genome") %>%
  dplyr::select(where(~ !all(. == 0))) %>%
  hilldiv(., q = 1, dist = dist) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(functional = 1) %>%
  rownames_to_column(var = "sample") %>%
  mutate(functional = if_else(is.nan(functional), 1, functional))

# Merge all metrics
alpha_div <- richness %>%
  full_join(neutral, by = join_by(sample == sample)) %>%
  full_join(phylogenetic, by = join_by(sample == sample)) %>%
  full_join(functional, by = join_by(sample == sample))
```

```{r alpha_div_diets_summary_all, comment="",echo=FALSE, message=FALSE, warning=FALSE}
alpha_div %>%
  pivot_longer(-sample, names_to = "alpha", values_to = "value") %>%
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
    group_by(alpha)%>%
    summarise(total_mean=mean(value, na.rm=T),
              total_sd=sd(value, na.rm=T),
              Xeric_shrubland_mean=mean(value[broad_environment=="1000218 - Xeric shrubland"], na.rm=T),
             Xeric_shrubland_sd=sd(value[broad_environment=="1000218 - Xeric shrubland"], na.rm=T),
             Cropland_mean=mean(value[broad_environment=="1000245 - Cropland"], na.rm=T),
             Cropland_sd=sd(value[broad_environment=="1000245 - Cropland"], na.rm=T),
              Mixed_forest_mean=mean(value[broad_environment=="1000198 - Mixed forest"], na.rm=T),
             Mixed_forest_sd=sd(value[broad_environment=="1000198 - Mixed forest"], na.rm=T),
              Temperate_woodland_mean=mean(value[broad_environment=="1000221 - Temperate woodland"], na.rm=T),
              Temperate_woodland_sd=sd(value[broad_environment=="1000221 - Temperate woodland"], na.rm=T)) %>%
    mutate(Total=str_c(round(total_mean,2),"±",round(total_sd,2)),
           Xeric_shrubland=str_c(round(Xeric_shrubland_mean,2),"±",round(Xeric_shrubland_sd,2)),
           Cropland=str_c(round(Cropland_mean,2),"±",round(Cropland_sd,2)),
           Mixed_forest=str_c(round(Mixed_forest_mean,2),"±",round(Mixed_forest_sd,2)),
           Temperate_woodland=str_c(round(Temperate_woodland_mean,2),"±",round(Temperate_woodland_sd,2))) %>% 
    arrange(-total_mean) %>% 
    dplyr::select(alpha,Total,Xeric_shrubland,Temperate_woodland,Cropland,Mixed_forest) %>% 
  tt()
```
Richness of microbiotic species - environment clusters
```{r alpha_div_boxplot, comment="", message=FALSE, warning=FALSE, fig.height=3, fig.width=10, fig.fullwidth=TRUE}
#Richness
plot1 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="richness") %>%
  ggplot(aes(y = value, x = broad_environment, group=broad_environment, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  scale_x_discrete(labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")) +
  stat_compare_means(method = "wilcox.test", show.legend = F, size = 3, label.y = c(300), label.x = c(1.5))+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Richness")


plot2 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="neutral") %>%
  ggplot(aes(y = value, x = broad_environment, group=broad_environment, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  scale_x_discrete(labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")) +
  stat_compare_means(method = "wilcox.test", show.legend = F, size = 3, label.y = c(190), label.x = c(1.5))+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Neutral alpha diversity")

plot3 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="phylogenetic") %>%
  ggplot(aes(y = value, x = broad_environment, group=broad_environment, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  scale_x_discrete(labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")) +
  stat_compare_means(method = "wilcox.test", show.legend = F, size = 3, label.y = c(12), label.x = c(1.5))+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Phylogenetic alpha diversity")


plot4 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="functional") %>%
  ggplot(aes(y = value, x = broad_environment, group=broad_environment, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  scale_x_discrete(labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")) +
  stat_compare_means(method = "wilcox.test", show.legend = F, size = 3, label.y = c(2), label.x = c(1.5))+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Functional alpha diversity")
```
```{r div_plot_together, comment="", echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
grid.arrange(arrangeGrob(plot1,plot2,plot3, plot4, ncol = 2))
```
Richness of microbiotic species - sex clusters
```{r alpha_div_boxplot_sex, comment="", message=FALSE, warning=FALSE, fig.height=3, fig.width=10, fig.fullwidth=TRUE}
#Richness
plot1 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="richness") %>%
  ggplot(aes(y = value, x = sex, group=sex, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  facet_grid(~factor(broad_environment, labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")), scale="free", space = "free")+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size = 12, lineheight = 0.6),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Richness")


plot2 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="neutral") %>%
  ggplot(aes(y = value, x = sex, group=sex, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  facet_grid(~factor(broad_environment, labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")), scale="free", space = "free")+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size = 12, lineheight = 0.6),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Neutral alpha diversity")

plot3 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="phylogenetic") %>%
  ggplot(aes(y = value, x = sex, group=sex, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  facet_grid(~factor(broad_environment, labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")), scale="free", space = "free")+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size = 12, lineheight = 0.6),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Phylogenetic alpha diversity")


plot4 <- alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == sample)) %>%
  filter(metric=="functional") %>%
  ggplot(aes(y = value, x = sex, group=sex, color=broad_environment, fill=broad_environment)) +
  geom_jitter(width = 0.2, show.legend = FALSE) +
  geom_boxplot(width = 0.5, alpha=0.5,outlier.shape = NA, show.legend = FALSE) +
  scale_color_manual(values=treatment_colors)+
  scale_fill_manual(values=treatment_colors) +
  facet_grid(~factor(broad_environment, labels=c("1000218 - Xeric shrubland" = "Xeric shrubland", "1000245 - Cropland" = "Cropland", "1000198 - Mixed forest" = "Mixed forest", "1000221 - Temperate woodland" = "Temperate woodland")), scale="free", space = "free")+
  coord_cartesian(xlim = c(1, NA)) +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(size = 12, lineheight = 0.6),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.text = element_text(size=10),
    axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))
    )+
  labs(y = "Functional alpha diversity")
```

```{r div_plot_together_sex, comment="", echo=FALSE, message=FALSE, warning=FALSE, fig.height=8, fig.width=10, fig.fullwidth=TRUE}
grid.arrange(arrangeGrob(plot1,plot2,plot3, plot4, ncol = 2))
```

### Mixed models

```{r rich_MM, comment="", message=FALSE, warning=FALSE}

alpha_div_meta <- alpha_div %>%
  left_join(sample_metadata, by = join_by(sample == sample))

alpha_div_meta_clean <- alpha_div_meta %>%
  filter(!is.na(richness), !is.na(broad_environment), !is.na(sex))

alpha_dic_meta_filtered_out <- anti_join(alpha_div_meta, alpha_div_meta_clean)

Model_richness_random <- lme(fixed = richness ~ broad_environment, data = alpha_div_meta_clean,
               random = ~ 1 | sex)
summary(Model_richness_random)

Model_richness<- lm(formula = richness ~ broad_environment+sex, data = alpha_div_meta_clean) 
summary(Model_richness)

Model_richness_sex_random <- lme(fixed = richness ~ sex, data = alpha_div_meta_clean,
               random = ~ 1 | broad_environment)
summary(Model_richness_sex_random)
emmeans(Model_richness_sex_random, pairwise ~ sex)
```

```{r neutral_MM, comment="", message=FALSE, warning=FALSE}
Model_neutral_random <- lme(fixed = neutral ~ broad_environment, data = alpha_div_meta_clean,
               random = ~ 1 | sex)
summary(Model_neutral_random)

Model_neutral<- lm(formula = neutral ~ broad_environment+sex, data = alpha_div_meta_clean) 
summary(Model_neutral)

Model_neutral_sex_random <- lme(fixed = neutral ~ sex, data = alpha_div_meta_clean,
               random = ~ 1 | broad_environment)
summary(Model_neutral_sex_random)
emmeans(Model_neutral_sex_random, pairwise ~ sex)
```

```{r phylo_MM, comment="", message=FALSE, warning=FALSE}

Model_phylogenetic<- lm(formula = phylogenetic ~ broad_environment+sex, data = alpha_div_meta_clean) 
summary(Model_phylogenetic)

Model_phylogenetic_sex_random <- lme(fixed = phylogenetic ~ sex, data = alpha_div_meta_clean,
               random = ~ 1 | broad_environment)

Model_phylogenetic_sex_random <- lme(fixed = phylogenetic ~ sex, data = alpha_div_meta_clean,
               random = ~ 1 | broad_environment)
summary(Model_phylogenetic_sex_random)
emmeans(Model_phylogenetic_sex_random, pairwise ~ sex)

```

```{r funct_MM, comment="", message=FALSE, warning=FALSE}
Model_functional_random <- lme(fixed = functional ~ broad_environment, data = alpha_div_meta_clean,
               random = ~ 1 | sex)
summary(Model_functional_random)

Model_functional<- lm(formula = functional ~ broad_environment+sex, data = alpha_div_meta_clean) 
summary(Model_functional)

Model_functional_sex_random <- lme(fixed = functional ~ sex, data = alpha_div_meta_clean,
               random = ~ 1 | broad_environment)
summary(Model_functional_sex_random)
emmeans(Model_functional_sex_random, pairwise ~ sex)
```
