# Inline Annotated R Markdown: 05_Differential_abundance_Inline_Annotated

## Code Chunk 1
```{r}
load("data/data.Rdata")  # Load an RData file with variables and datasets
```

## Code Chunk 2
```{r}
# phyloseq object considering structual zeros
phylo_samples <- sample_metadata %>%
  column_to_rownames("sample") %>%
  sample_data() # convert to phyloseq sample_data object

phylo_genome <- genome_counts_filt %>%
  column_to_rownames("genome") %>%
  mutate_all(~ replace(., . == 0, 0.00001)) %>% # add pseudo counts to avoid structural zero issues (note this approach can be improved!) %>%
  mutate_all(~./sum(.)) %>% #apply TSS nornalisation
  otu_table(., taxa_are_rows = TRUE)

phylo_taxonomy <- genome_metadata %>%
  filter(genome %in% rownames(phylo_genome)) %>% # remove structural zeros  # Filter the data to include only rows that meet certain conditions
  mutate(genome2 = genome) %>% # create a pseudo genome name column  # Add or modify columns in the dataset
  column_to_rownames("genome2") %>%
  dplyr::select(domain, phylum, class, order, family, genus, species, genome) %>% # add an additional taxonomic level to ensure genome-level analysis (as no all genomes have species-level taxonomic assignments. Otherwise, ANCOMBC2 aggregates analyses per species)  # Select specific columns from the data
  as.matrix() %>%
  tax_table() # convert to phyloseq tax_table object

phyloseq <- phyloseq(phylo_genome, phylo_taxonomy, phylo_samples)
```

## Code Chunk 3
```{r}
differential_abundance <- ancombc2(
  data = phyloseq,
  assay_name = "counts",
  tax_level = NULL, # change to agglomerate analysis to a higher taxonomic range
  fix_formula = "type", # fixed variable(s)
  rand_formula = "(1|individual)",
  p_adj_method = "holm",
  pseudo_sens = TRUE,
  prv_cut = 0,
  lib_cut = 0,
  s0_perc = 0.05,
  group = NULL,
  struc_zero = FALSE,
  neg_lb = FALSE,
  alpha = 0.05,
  n_cl = 2,
  verbose = TRUE,
  global = FALSE,
  pairwise = FALSE,
  dunnet = FALSE,
  trend = FALSE,
  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
  em_control = list(tol = 1e-5, max_iter = 100),
  lme_control = lme4::lmerControl(),
  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
  trend_control = NULL
)

# Save differential abundance to data object

save(sample_metadata, 
     genome_metadata, 
     read_counts, 
     genome_counts, 
     genome_counts_filt, 
     genome_tree,
     genome_gifts, 
     phylum_colors,
     data_stats,
     differential_abundance,
     file = "resources/data.Rdata")
```

## Code Chunk 4
```{r}
tax <- data.frame(phyloseq@tax_table) %>%
  rownames_to_column(., "taxon")

differential_abundance_table <- differential_abundance$res %>%
  dplyr::select(genome=taxon, lfc_typefeces, p_typefeces) %>%  # Select specific columns from the data
  filter(p_typefeces < 0.05) %>%  # Filter the data to include only rows that meet certain conditions
  dplyr::arrange(p_typefeces) %>%
  merge(., tax, by = "genome")

differential_abundance_table %>%
  select(genome,order,phylum, lfc_typefeces, p_typefeces) %>%  # Select specific columns from the data
  tt()
```

## Code Chunk 5
```{r}
ggplot(differential_abundance_table, aes(x = forcats::fct_rev(genome), y = lfc_typefeces, color = phylum)) +  # Begin plotting using ggplot2
  geom_point(size = 3) +  # Add a specific type of plot layer (bars, points, lines, etc.)
  scale_color_manual(values = phylum_colors[-c(3,4)]) +  # Adjust color scales, axes, or fill options
  geom_hline(yintercept = 0) +  # Add a specific type of plot layer (bars, points, lines, etc.)
  coord_flip() +
  facet_grid(phylum ~ ., scales = "free", space = "free") +  # Create multiple subplots based on a variable
  theme(  # Customize visual aspects of the plot
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    axis.title.x = element_blank(),
    strip.background = element_blank(), 
    strip.text = element_blank()
  ) +
  xlab("Genome") +
  ylab("log2FoldChange") +
  guides(col = guide_legend("Phylum"))
```

## Code Chunk 6
```{r}
differential_abundance$res %>%
  na.omit() %>%
  dplyr::select(genome=taxon, lfc_typefeces, p_typefeces) %>%  # Select specific columns from the data
  left_join(genome_metadata, by = join_by(genome == genome)) %>%  # Merge two datasets, keeping all rows from the left one
  mutate(phylum = ifelse(p_typefeces < 0.05, phylum, NA)) %>%  # Add or modify columns in the dataset
  ggplot(., aes(x = lfc_typefeces, y = -log(p_typefeces), color = phylum)) +  # Begin plotting using ggplot2
  geom_point() +  # Add a specific type of plot layer (bars, points, lines, etc.)
  #xlim(c(-10,4)) +
  scale_color_manual(values = phylum_colors[-c(3,4)]) +  # Adjust color scales, axes, or fill options
  labs(color = "Significance", x = "Log-fold difference between sample types", y = "p-value") +  # Customize axis labels or plot titles
  theme_classic()
```

## Code Chunk 7
```{r}
differential_abundance_genus <- ancombc2(
  data = phyloseq,
  assay_name = "counts",
  tax_level = "genus", # change to agglomerate analysis to a higher taxonomic range
  fix_formula = "type", # fixed variable(s)
  rand_formula = "(1|individual)",
  p_adj_method = "holm",
  pseudo_sens = TRUE,
  prv_cut = 0,
  lib_cut = 0,
  s0_perc = 0.05,
  group = NULL,
  struc_zero = FALSE,
  neg_lb = FALSE,
  alpha = 0.05,
  n_cl = 2,
  verbose = TRUE,
  global = FALSE,
  pairwise = FALSE,
  dunnet = FALSE,
  trend = FALSE,
  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
  em_control = list(tol = 1e-5, max_iter = 100),
  lme_control = lme4::lmerControl(),
  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
  trend_control = NULL
)

# Save differential abundance to data object

save(sample_metadata, 
     genome_metadata, 
     read_counts, 
     genome_counts, 
     genome_counts_filt, 
     genome_tree,
     genome_gifts, 
     phylum_colors,
     data_stats,
     differential_abundance,
     differential_abundance_genus,
     file = "resources/data.Rdata")
```

## Code Chunk 8
```{r}
tax <- data.frame(phyloseq@tax_table) %>%
  rownames_to_column(., "taxon")

differential_abundance_genus$res %>%
  filter(nchar(taxon) > 5) %>%  # Filter the data to include only rows that meet certain conditions
  dplyr::select(taxon=taxon, lfc_typefeces, p_typefeces) %>%  # Select specific columns from the data
  filter(p_typefeces < 0.05) %>%  # Filter the data to include only rows that meet certain conditions
  dplyr::arrange(lfc_typefeces) %>%
  left_join(tax %>% select(-c(taxon,genome,species)) %>% unique(), by = join_by(taxon==genus)) %>%  # Select specific columns from the data
  tt()
```

## Code Chunk 9
```{r}
differential_abundance_phylum <- ancombc2(
  data = phyloseq,
  assay_name = "counts",
  tax_level = "phylum", # change to agglomerate analysis to a higher taxonomic range
  fix_formula = "type", # fixed variable(s)
  rand_formula = "(1|individual)",
  p_adj_method = "holm",
  pseudo_sens = TRUE,
  prv_cut = 0,
  lib_cut = 0,
  s0_perc = 0.05,
  group = NULL,
  struc_zero = FALSE,
  neg_lb = FALSE,
  alpha = 0.05,
  n_cl = 2,
  verbose = TRUE,
  global = FALSE,
  pairwise = FALSE,
  dunnet = FALSE,
  trend = FALSE,
  iter_control = list(tol = 1e-5, max_iter = 20, verbose = FALSE),
  em_control = list(tol = 1e-5, max_iter = 100),
  lme_control = lme4::lmerControl(),
  mdfdr_control = list(fwer_ctrl_method = "holm", B = 100),
  trend_control = NULL
)

# Save differential abundance to data object
save(sample_metadata, 
     genome_metadata, 
     read_counts, 
     genome_counts, 
     genome_counts_filt, 
     genome_tree,
     genome_gifts, 
     phylum_colors,
     data_stats,
     differential_abundance,
     differential_abundance_genus,
     differential_abundance_phylum,
     file = "resources/data.Rdata")
```

## Code Chunk 10
```{r}
differential_abundance_phylum_table <- differential_abundance_phylum$res %>%
  dplyr::select(taxon=taxon, lfc_typefeces, p_typefeces) %>%  # Select specific columns from the data
  #filter(p_typefeces < 0.05) %>%  # Filter the data to include only rows that meet certain conditions
  dplyr::arrange(lfc_typefeces)


phylum_colors2 <- read_tsv("https://raw.githubusercontent.com/earthhologenome/EHI_taxonomy_colour/main/ehi_phylum_colors.tsv") %>%
    left_join(differential_abundance_phylum_table, by=join_by(phylum == taxon)) %>%  # Merge two datasets, keeping all rows from the left one
    arrange(match(phylum, differential_abundance_phylum_table$taxon)) %>%
    select(phylum, colors) %>%   # Select specific columns from the data
    unique() %>%
    select(colors) %>%  # Select specific columns from the data
    pull()

differential_abundance_phylum_table %>%
  filter(p_typefeces < 0.05) %>%  # Filter the data to include only rows that meet certain conditions
  dplyr::arrange(lfc_typefeces) %>%
  tt()
```

## Code Chunk 11
```{r}
differential_abundance_phylum_table %>%
      mutate(taxon=factor(taxon,levels=differential_abundance_phylum_table$taxon)) %>%  # Add or modify columns in the dataset
      ggplot(aes(x = lfc_typefeces, y = forcats::fct_rev(taxon), fill = taxon)) +  # Begin plotting using ggplot2
        geom_col(size = 2) +  # Add a specific type of plot layer (bars, points, lines, etc.)
        scale_fill_manual(values = phylum_colors2) +  # Adjust color scales, axes, or fill options
        geom_hline(yintercept = 0) +  # Add a specific type of plot layer (bars, points, lines, etc.)
        geom_vline(xintercept = 4, linetype="dashed", color = "grey", size=1) +  # Add a specific type of plot layer (bars, points, lines, etc.)
        geom_vline(xintercept = -4, linetype="dashed", color = "grey", size=1) +  # Add a specific type of plot layer (bars, points, lines, etc.)
        theme(  # Customize visual aspects of the plot
          panel.background = element_blank(),
          axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
          axis.title.x = element_blank(),
          strip.background = element_blank(), 
          strip.text = element_blank()
        ) +
        labs(x="log2FoldChange", y="Phylum")  # Customize axis labels or plot titles
```

