
# Beta diversity

```{r load_data_beta}
load("data/data.Rdata")

treatment_colors <- c("#f56042","#429ef5", "#42f58d", "#b142f5", "#f5e642")
```

```{r filter_NAs}
sample_metadata_without_NA <- sample_metadata %>%
  filter(!is.na(broad_environment))
```

***beta_div***
```{r beta_div, comment="", message=FALSE, warning=FALSE, eval=FALSE}
#Presence/Absence
beta_q0n <- genome_counts_filt %>%  f
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 0)
#Abundance-sensitive
beta_q1n <- genome_counts_filt %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 1)
#Abundance + Phylogeny
genome_counts_filt_beta <- genome_counts_filt %>%
  column_to_rownames(., "genome") %>% 
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0))%>%
  rownames_to_column(., "genome")
#Abundance + Trait Distance
genome_tree <- keep.tip(genome_tree, tip=genome_counts_filt_beta$genome)
beta_q1p <- genome_counts_filt %>%  
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0)) %>%
  hillpair(., q = 1, tree = genome_tree)
```

```{r beta_div2, comment="", message=FALSE, warning=FALSE, eval=TRUE}

# 1. Only use genomes that also occur in genome_gifts
valid_genomes <- genome_counts_filt_beta$genome[genome_counts_filt_beta$genome %in% rownames(genome_gifts)]

# 2. filter genome_gifts on these genomes
genome_gifts1 <- genome_gifts[valid_genomes, ]
genome_gifts1 <- genome_gifts1[, colSums(genome_gifts1 != 0) > 0]

# 3. Calculate functional distance matrix
dist <- genome_gifts1 %>%
  to.elements(., GIFT_db) %>%
  traits2dist(., method = "gower")

# 4. Determine genomes that exist in both genome_counts_filt_beta and dist
common_genomes <- intersect(
  genome_counts_filt_beta$genome,
  rownames(dist)
)

# 5. genome_counts_filt to filter and sort the shared genomes
genome_counts_filt_matched <- genome_counts_filt %>%
  column_to_rownames("genome") %>%
  filter(rownames(.) %in% common_genomes) %>%
  select_if(~!all(. == 0))  # optional: leere Spalten raus

# 6. Limit and sort dist matrix to common genomes
dist_matched <- dist[common_genomes, common_genomes]


beta_q1f <- genome_counts_filt_matched %>%
  hillpair(q = 1, dist = dist_matched)


```

```{r save_beta, comment="", message=FALSE,echo=FALSE,warning=FALSE, eval=FALSE}
save(beta_q0n, 
     beta_q1n, 
     beta_q1p, 
     beta_q1f, 
     file = "data/beta.Rdata")
```


```{r seed, comment="", message=FALSE,echo=FALSE,warning=FALSE, eval=FALSE}

set.seed(2025)
```

## Permanova

```{r Funktion für PERMANOVA Analysen, comment="", message=FALSE, warning=FALSE}
run_permanova <- function(beta_matrix, metadata, sample_col = "sample", group_col, group_vars, pairwise = FALSE) {
  
  # 1. Sample labels from Beta-Matrix
  sample_labels <- labels(beta_matrix$S)
  
  # 2. Metadata filtered and sorted
  metadata_matched <- metadata %>%
    filter(!!sym(sample_col) %in% sample_labels) %>%
    arrange(match(!!sym(sample_col), sample_labels))
  
  # 3. Synchronize beta_matrix$S to metadata
  common_samples <- intersect(sample_labels, metadata_matched[[sample_col]])
  beta_matrix$S <- beta_matrix$S[common_samples, common_samples]
  metadata_matched <- metadata_matched %>%
    filter(!!sym(sample_col) %in% common_samples) %>%
    arrange(match(!!sym(sample_col), common_samples))
  
  # 4. Remove samples with NA in group_col
  valid_idx <- !is.na(metadata_matched[[group_col]])
  beta_matrix$S <- beta_matrix$S[valid_idx, valid_idx]
  metadata_matched <- metadata_matched[valid_idx, ]
  
  # 5. Betadisper and Permutest
  cat("\n===== Beta Dispersion Test =====\n")
  dispersion_result <- betadisper(beta_matrix$S, metadata_matched[[group_col]])
  print(permutest(dispersion_result))
  
  # 6. Dynamic formula building
  formula_str <- paste0("beta_matrix$S ~ ", paste(group_vars, collapse = " + "))
  cat("\n===== PERMANOVA Test (adonis2) =====\n")
  permanova_result <- adonis2(as.formula(formula_str),
                              data = metadata_matched,
                              permutations = 999,
                              by = "terms")
  print(broom::tidy(permanova_result))
  
  # 7. (Optional) Pairwise Adonis
  if (pairwise) {
    cat("\n===== Pairwise PERMANOVA =====\n")
    print(pairwise.adonis(beta_matrix$S, metadata_matched[[group_col]], perm = 999))
  }
  
  # 8. Return outputs
  return(list(
    dispersion = dispersion_result,
    permanova = permanova_result
  ))
}
```

### Richness

```{r permanova_richness, comment="", message=FALSE, warning=FALSE, eval = FALSE}

run_permanova(
  beta_matrix = beta_q0n$S,
  metadata = sample_metadata_without_NA,
  sample_col = "sample",
  group_col = "broad_environment",
  group_vars = c("broad_environment","sex", "broad_environment:sex"),
  pairwise = FALSE
)

```

### Neutral diversity

```{r permanova_neutral, comment="", message=FALSE, warning=FALSE, eval = FALSE}
run_permanova(
  beta_matrix = beta_q1n,
  metadata = sample_metadata_without_NA,
  sample_col = "sample",
  group_col = "broad_environment",
  group_vars = c("broad_environment","sex", "broad_environment:sex"),
  pairwise = TRUE
)
```

### Phylogenetic diversity (beta_q1p)

```{r permanova_phylo, comment="", message=FALSE, warning=FALSE, eval = FALSE}

run_permanova(
  beta_matrix = beta_q1p,
  metadata = sample_metadata_without_NA,
  sample_col = "sample",
  group_col = "broad_environment",
  group_vars = c("broad_environment","sex", "broad_environment:sex"),
  pairwise = FALSE  # no pairwise comparisons here
)
```

### Functional diversity (beta_q1f)

```{r permanova_func, comment="", message=FALSE, warning=FALSE, eval = FALSE}

run_permanova(
  beta_matrix = beta_q1f,
  metadata = sample_metadata_without_NA,
  sample_col = "sample",
  group_col = "broad_environment",
  group_vars = c("broad_environment","sex", "broad_environment:sex"),
  pairwise = TRUE  
)
```

## NMDS 
non-metric multidimensional scaling on species-richness - environment clusters

###Richness
```{r beta_div_nmds_richness_plot, comment="", message=FALSE, warning=FALSE, fig.height=7, fig.width=10, fig.fullwidth=TRUE}
beta_q0n$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  group_by(broad_environment) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = NMDS1, y = NMDS2, color = broad_environment, shape = as.factor(sex))) +
  geom_point(size = 4) +
  scale_color_manual(values = treatment_colors,labels=c("high" = "High-altitude", "low" = "Low-altitude")) +
  geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.9, show.legend = FALSE) +
  theme(
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.position = "right", legend.box = "vertical"
    ) +
    labs(color="Environmental context", shape="sex")+geom_text_repel(aes(label = sample), size=3)

```


### Neutral diversity

```{r beta_div_nmds_neutral_plot, comment="", message=FALSE, warning=FALSE, fig.height=7, fig.width=10, fig.fullwidth=TRUE}
beta_q1n$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  group_by(broad_environment) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = NMDS1, y = NMDS2, color = broad_environment, shape = as.factor(sex))) +
  geom_point(size = 4) +
  scale_color_manual(values = treatment_colors,labels=c("high" = "High-altitude", "low" = "Low-altitude")) +
  geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.9, show.legend = FALSE) +
  theme(
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.position = "right", legend.box = "vertical"
    ) +
    labs(color="Evironmental context", shape="sex")
```

### Phylogenetic diversity

```{r beta_div_nmds_phylo_plot, comment="", message=FALSE, warning=FALSE, fig.height=7, fig.width=10, fig.fullwidth=TRUE}
beta_q1p$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  group_by(broad_environment) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = NMDS1, y = NMDS2, color = broad_environment, shape = as.factor(sex))) +
  geom_point(size = 4) +
  scale_color_manual(values = treatment_colors,labels=c("high" = "High-altitude", "low" = "Low-altitude")) +
  geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.9, show.legend = FALSE) +
  theme(
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.position = "right", legend.box = "vertical"
    ) +
    labs(color="environment context", shape="sex")+geom_text_repel(aes(label = sample), size=3)
```


### Functional diversity

```{r beta_div_nmds_funct_plot, comment="", message=FALSE, warning=FALSE, fig.height=7, fig.width=10, fig.fullwidth=TRUE}
 beta_q1f$S %>%
  vegan::metaMDS(., trymax = 500, k = 2, trace=0) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  dplyr::left_join(sample_metadata, by = join_by(sample == sample)) %>%
  group_by(broad_environment) %>%
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = NMDS1, y = NMDS2, color = broad_environment, shape = as.factor(sex))) +
  geom_point(size = 4) +
  scale_color_manual(values = treatment_colors,labels=c("high" = "High-altitude", "low" = "Low-altitude")) +
  geom_segment(aes(x = x_cen, y = y_cen, xend = NMDS1, yend = NMDS2), alpha = 0.9, show.legend = FALSE) +
  theme(
    axis.title = element_text(size = 12, face = "bold"),
    axis.text = element_text(size = 10),
    panel.background = element_blank(),
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    legend.position = "right", legend.box = "vertical"
    ) +
    labs(color="broad_environment", shape="sex")+geom_text_repel(aes(label = sample), size=3)
```

