> **Archived (former chapter 13).** Legacy r100/r200/r400/tasmania setup. See `archive/README.md`.

# BTP Hmsc

```{r load_libraries, comment="", message=FALSE, warning=FALSE}
library(tidyverse)
library(Hmsc)
library(ape)
```

## 100m buffer

```{r load_data_r100, comment="", message=FALSE, warning=FALSE}
load("data/data.Rdata")

animal_variables <- read_csv("data/animal_var.csv")
location_variables <- read_csv("data/environment_var_r100.csv")

predictors <- inner_join(animal_variables,location_variables,by="id") %>% 
  rename(sample=id)
```

```{r filter_genomes_r100, comment="", message=FALSE, warning=FALSE}
prevalent_genomes <- genome_counts_filt %>% 
  rowwise() %>%
  mutate(nonzero_prop = mean(c_across(-genome) > 0)) %>%
  ungroup() %>%
  filter(nonzero_prop > 0.10) %>%
  select(-nonzero_prop) %>%
  pull(genome)

widespread_genomes <-genome_counts_filt %>%
  pivot_longer(!genome,names_to = "sample",values_to = "count") %>% 
  left_join(location_variables,by=join_by("sample"=="id")) %>% 
  group_by(genome,site) %>% 
  summarise(nonzero_samples = sum(count > 0), .groups = "drop") %>% 
  group_by(genome) %>% 
  summarise(nonzero_sites = sum(nonzero_samples > 0), .groups = "drop") %>% 
  filter(nonzero_sites>5) %>% 
  pull(genome)

genomes_to_model <- intersect(prevalent_genomes,widespread_genomes)
```

```{r hmsc_input_red_r100, warning=FALSE, comments="", message=FALSE}
# Random effects data (study design)
StudyDesign <- predictors %>%
                    select(sample,site) %>%
                    mutate(animal=sample) %>% 
                    mutate(animal = factor(animal), site = factor(site)) %>%
                    column_to_rownames("sample")

# Genome count table (quantitative community data; length-normalised per genome ID)
YData <- read_counts %>%
  left_join(
    genome_metadata %>% mutate(norm_factor = median(length) / length) %>% select(genome, norm_factor),
    by = "genome"
  ) %>%
  mutate(across(-c(genome, norm_factor), ~ round(. * norm_factor, 0))) %>%
  select(-norm_factor) %>%
                    mutate(across(where(is.numeric), ~ . +1 )) %>% #add +1 pseudocount to remove zeros
                    mutate(across(where(is.numeric), ~  log(.) )) %>% #log-transform
                    filter(genome %in% genomes_to_model) %>% 
                    column_to_rownames("genome") %>%
                    select(all_of(row.names(StudyDesign))) %>%  
                    as.data.frame() %>%
                    t() # transpose

# Fixed effects data (explanatory variables) 
XData <- predictors %>%
                    select(sample,weight,development,temperature,precipitation,diversity,density,devil) %>%
                    mutate(development = factor(development) ) %>%
                    mutate(logseqdepth=read_counts %>% #total log-sequencing depth
                        select(all_of(row.names(StudyDesign))) %>%
                        colSums() %>%
                        log()
                    ) %>%
                    column_to_rownames("sample")

# Genome phylogeny
PData <- genome_tree %>% 
    keep.tip(tip=genomes_to_model)
```

```{r hmsc_formulas_r100, warning=FALSE, comments="", message=FALSE}

# Fixed effects formula
XFormula = ~weight + development + diversity + temperature + precipitation + density + devil + logseqdepth

# Study design
rL.animal = HmscRandomLevel(units = levels(StudyDesign$animal))
rL.site = HmscRandomLevel(units = levels(StudyDesign$site))
```

```{r hmsc_models_r100, warning=FALSE, comments="", message=FALSE}
#Define model
m = Hmsc(Y=YData,
         XData = XData,
         XFormula = XFormula,
         studyDesign = StudyDesign,
         phyloTree = PData,
         ranLevels = list("animal"=rL.animal, "site"=rL.site),
         distr = "normal",
         YScale = TRUE)

save(m, file = "hmsc/model_r100")
```

## In the HPC

```{sh, eval=FALSE}
conda activate hmsc-hpc

model="hmsc/model_r100"
init="init/model_r100.rds"

export samples=250
export thin=1000
export transient=$(( samples * thin ))
export nChains=4
export verbose=TRUE
export model
export init

# Get initiation object
Rscript hmsc.r $model $init
```

```{sh, eval=FALSE}
cat <<'EOF' > launch_hmsc_model_r100.sh
#!/bin/bash
#SBATCH --job-name=hmsc_model_r100
#SBATCH --nodes=1
#SBATCH --partition=cpuqueue
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=32gb
#SBATCH --time=150:00:00

# Activate conda environment
source activate hmsc-hpc

# Set output files
output="output/Hmsc_model_r100.rds"
mkdir output

# Run model fit
srun python3 -m hmsc.run_gibbs_sampler --input $init --output $output --samples $samples --transient $transient --thin $thin --verbose 100
EOF
```

```{sh, eval=FALSE}
sbatch launch_hmsc_model_r100.sh
```

## 200m buffer

```{r load_data_r200, comment="", message=FALSE, warning=FALSE}
load("data/data.Rdata")

animal_variables <- read_csv("data/animal_var.csv")
location_variables <- read_csv("data/environment_var_r200.csv")

predictors <- inner_join(animal_variables,location_variables,by="id") %>% 
  rename(sample=id)
```

```{r filter_genomes_r200, comment="", message=FALSE, warning=FALSE}
prevalent_genomes <- genome_counts_filt %>% 
  rowwise() %>%
  mutate(nonzero_prop = mean(c_across(-genome) > 0)) %>%
  ungroup() %>%
  filter(nonzero_prop > 0.10) %>%
  select(-nonzero_prop) %>%
  pull(genome)

widespread_genomes <-genome_counts_filt %>%
  pivot_longer(!genome,names_to = "sample",values_to = "count") %>% 
  left_join(location_variables,by=join_by("sample"=="id")) %>% 
  group_by(genome,site) %>% 
  summarise(nonzero_samples = sum(count > 0), .groups = "drop") %>% 
  group_by(genome) %>% 
  summarise(nonzero_sites = sum(nonzero_samples > 0), .groups = "drop") %>% 
  filter(nonzero_sites>5) %>% 
  pull(genome)

genomes_to_model <- intersect(prevalent_genomes,widespread_genomes)
```

```{r hmsc_input_red_r200, warning=FALSE, comments="", message=FALSE}
# Random effects data (study design)
StudyDesign <- predictors %>%
                    select(sample,site) %>%
                    mutate(animal=sample) %>% 
                    mutate(animal = factor(animal), site = factor(site)) %>%
                    column_to_rownames("sample")

# Genome count table (quantitative community data; length-normalised per genome ID)
YData <- read_counts %>%
  left_join(
    genome_metadata %>% mutate(norm_factor = median(length) / length) %>% select(genome, norm_factor),
    by = "genome"
  ) %>%
  mutate(across(-c(genome, norm_factor), ~ round(. * norm_factor, 0))) %>%
  select(-norm_factor) %>%
                    mutate(across(where(is.numeric), ~ . +1 )) %>% #add +1 pseudocount to remove zeros
                    mutate(across(where(is.numeric), ~  log(.) )) %>% #log-transform
                    filter(genome %in% genomes_to_model) %>% 
                    column_to_rownames("genome") %>%
                    select(all_of(row.names(StudyDesign))) %>%  
                    as.data.frame() %>%
                    t() # transpose

# Fixed effects data (explanatory variables) 
XData <- predictors %>%
                    select(sample,weight,development,temperature,precipitation,diversity,density,devil) %>%
                    mutate(development = factor(development) ) %>%
                    mutate(logseqdepth=read_counts %>% #total log-sequencing depth
                        select(all_of(row.names(StudyDesign))) %>%
                        colSums() %>%
                        log()
                    ) %>%
                    column_to_rownames("sample")

# Genome phylogeny
PData <- genome_tree %>% 
    keep.tip(tip=genomes_to_model)
```

```{r hmsc_formulas_r200, warning=FALSE, comments="", message=FALSE}

# Fixed effects formula
XFormula = ~weight + development + diversity + temperature + precipitation + density + devil + logseqdepth

# Study design
rL.animal = HmscRandomLevel(units = levels(StudyDesign$animal))
rL.site = HmscRandomLevel(units = levels(StudyDesign$site))
```

```{r hmsc_models_r200, warning=FALSE, comments="", message=FALSE}
#Define model
m = Hmsc(Y=YData,
         XData = XData,
         XFormula = XFormula,
         studyDesign = StudyDesign,
         phyloTree = PData,
         ranLevels = list("animal"=rL.animal, "site"=rL.site),
         distr = "normal",
         YScale = TRUE)

save(m, file = "hmsc/model_r200")
```

## In the HPC

```{sh, eval=FALSE}
conda activate hmsc-hpc

model="hmsc/model_r200"
init="init/model_r200.rds"

export samples=250
export thin=1000
export transient=$(( samples * thin ))
export nChains=4
export verbose=TRUE
export model
export init

# Get initiation object
Rscript hmsc.r $model $init
```

```{sh, eval=FALSE}
cat <<'EOF' > launch_hmsc_model_r200.sh
#!/bin/bash
#SBATCH --job-name=hmsc_model_r200
#SBATCH --nodes=1
#SBATCH --partition=cpuqueue
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=32gb
#SBATCH --time=150:00:00

# Activate conda environment
source activate hmsc-hpc

# Set output files
output="output/Hmsc_model_r200.rds"
mkdir output

# Run model fit
srun python3 -m hmsc.run_gibbs_sampler --input $init --output $output --samples $samples --transient $transient --thin $thin --verbose 100
EOF
```

```{sh, eval=FALSE}
sbatch launch_hmsc_model_r200.sh
```

## 400m buffer

```{r load_data_r400, comment="", message=FALSE, warning=FALSE}
load("data/data.Rdata")

animal_variables <- read_csv("data/animal_var.csv")
location_variables <- read_csv("data/environment_var_r400.csv")

predictors <- inner_join(animal_variables,location_variables,by="id") %>% 
  rename(sample=id)
```

```{r filter_genomes_r400, comment="", message=FALSE, warning=FALSE}
prevalent_genomes <- genome_counts_filt %>% 
  rowwise() %>%
  mutate(nonzero_prop = mean(c_across(-genome) > 0)) %>%
  ungroup() %>%
  filter(nonzero_prop > 0.10) %>%
  select(-nonzero_prop) %>%
  pull(genome)

widespread_genomes <-genome_counts_filt %>%
  pivot_longer(!genome,names_to = "sample",values_to = "count") %>% 
  left_join(location_variables,by=join_by("sample"=="id")) %>% 
  group_by(genome,site) %>% 
  summarise(nonzero_samples = sum(count > 0), .groups = "drop") %>% 
  group_by(genome) %>% 
  summarise(nonzero_sites = sum(nonzero_samples > 0), .groups = "drop") %>% 
  filter(nonzero_sites>5) %>% 
  pull(genome)

genomes_to_model <- intersect(prevalent_genomes,widespread_genomes)
```

```{r hmsc_input_red_r400, warning=FALSE, comments="", message=FALSE}
# Random effects data (study design)
StudyDesign <- predictors %>%
                    select(sample,site) %>%
                    mutate(animal=sample) %>% 
                    mutate(animal = factor(animal), site = factor(site)) %>%
                    column_to_rownames("sample")

# Genome count table (quantitative community data; length-normalised per genome ID)
YData <- read_counts %>%
  left_join(
    genome_metadata %>% mutate(norm_factor = median(length) / length) %>% select(genome, norm_factor),
    by = "genome"
  ) %>%
  mutate(across(-c(genome, norm_factor), ~ round(. * norm_factor, 0))) %>%
  select(-norm_factor) %>%
                    mutate(across(where(is.numeric), ~ . +1 )) %>% #add +1 pseudocount to remove zeros
                    mutate(across(where(is.numeric), ~  log(.) )) %>% #log-transform
                    filter(genome %in% genomes_to_model) %>% 
                    column_to_rownames("genome") %>%
                    select(all_of(row.names(StudyDesign))) %>%  
                    as.data.frame() %>%
                    t() # transpose

# Fixed effects data (explanatory variables) 
XData <- predictors %>%
                    select(sample,weight,development,temperature,precipitation,diversity,density,devil) %>%
                    mutate(development = factor(development) ) %>%
                    mutate(logseqdepth=read_counts %>% #total log-sequencing depth
                        select(all_of(row.names(StudyDesign))) %>%
                        colSums() %>%
                        log()
                    ) %>%
                    column_to_rownames("sample")

# Genome phylogeny
PData <- genome_tree %>% 
    keep.tip(tip=genomes_to_model)
```

```{r hmsc_formulas_r400, warning=FALSE, comments="", message=FALSE}

# Fixed effects formula
XFormula = ~weight + development + diversity + temperature + precipitation + density + devil + logseqdepth

# Study design
rL.animal = HmscRandomLevel(units = levels(StudyDesign$animal))
rL.site = HmscRandomLevel(units = levels(StudyDesign$site))
```

```{r hmsc_models_r400, warning=FALSE, comments="", message=FALSE}
#Define model
m = Hmsc(Y=YData,
         XData = XData,
         XFormula = XFormula,
         studyDesign = StudyDesign,
         phyloTree = PData,
         ranLevels = list("animal"=rL.animal, "site"=rL.site),
         distr = "normal",
         YScale = TRUE)

save(m, file = "hmsc/model_r400")
```

## In the HPC

```{sh, eval=FALSE}
conda activate hmsc-hpc

model="hmsc/model_r400"
init="init/model_r400.rds"

export samples=250
export thin=1000
export transient=$(( samples * thin ))
export nChains=4
export verbose=TRUE
export model
export init

# Get initiation object
Rscript hmsc.r $model $init
```

```{sh, eval=FALSE}
cat <<'EOF' > launch_hmsc_model_r400.sh
#!/bin/bash
#SBATCH --job-name=hmsc_model_r400
#SBATCH --nodes=1
#SBATCH --partition=cpuqueue
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=32gb
#SBATCH --time=150:00:00

# Activate conda environment
source activate hmsc-hpc

# Set output files
output="output/Hmsc_model_r400.rds"
mkdir output

# Run model fit
srun python3 -m hmsc.run_gibbs_sampler --input $init --output $output --samples $samples --transient $transient --thin $thin --verbose 100
EOF
```

```{sh, eval=FALSE}
sbatch launch_hmsc_model_r400.sh
```

## tasmania only buffer

```{r load_data_tasmania, comment="", message=FALSE, warning=FALSE}
load("data/data.Rdata")

animal_variables <- read_csv("data/animal_var.csv")
location_variables <- read_csv("data/environment_var_r400.csv")

predictors <- inner_join(animal_variables, location_variables, by = "id") %>%
  rename(sample = id) %>%
  filter(sample %in% sample_metadata$sample[sample_metadata$island == "Tasmania"])
```

```{r filter_genomes_tasmania, comment="", message=FALSE, warning=FALSE}
tasmania_samples <- predictors$sample
genome_counts_tasmania <- genome_counts_filt %>%
  dplyr::select(genome, dplyr::all_of(tasmania_samples))

prevalent_genomes <- genome_counts_tasmania %>% 
  rowwise() %>%
  mutate(nonzero_prop = mean(c_across(-genome) > 0)) %>%
  ungroup() %>%
  filter(nonzero_prop > 0.10) %>%
  select(-nonzero_prop) %>%
  pull(genome)

widespread_genomes <- genome_counts_tasmania %>%
  pivot_longer(!genome,names_to = "sample",values_to = "count") %>% 
  left_join(predictors %>% select(sample, site), by = join_by(sample == sample)) %>% 
  group_by(genome,site) %>% 
  summarise(nonzero_samples = sum(count > 0), .groups = "drop") %>% 
  group_by(genome) %>% 
  summarise(nonzero_sites = sum(nonzero_samples > 0), .groups = "drop") %>% 
  filter(nonzero_sites>5) %>% 
  pull(genome)

genomes_to_model <- intersect(prevalent_genomes,widespread_genomes)
```

```{r hmsc_input_red_tasmania, warning=FALSE, comments="", message=FALSE}
# Random effects data (study design)
StudyDesign <- predictors %>%
                    select(sample,site) %>%
                    mutate(animal=sample) %>% 
                    mutate(animal = factor(animal), site = factor(site)) %>%
                    column_to_rownames("sample")

# Genome count table (quantitative community data; length-normalised per genome ID)
YData <- read_counts %>%
  left_join(
    genome_metadata %>% mutate(norm_factor = median(length) / length) %>% select(genome, norm_factor),
    by = "genome"
  ) %>%
  mutate(across(-c(genome, norm_factor), ~ round(. * norm_factor, 0))) %>%
  select(-norm_factor) %>%
                    mutate(across(where(is.numeric), ~ . +1 )) %>% #add +1 pseudocount to remove zeros
                    mutate(across(where(is.numeric), ~  log(.) )) %>% #log-transform
                    filter(genome %in% genomes_to_model) %>% 
                    column_to_rownames("genome") %>%
                    select(all_of(row.names(StudyDesign))) %>%  
                    as.data.frame() %>%
                    t() # transpose

# Fixed effects data (explanatory variables) 
XData <- predictors %>%
                    select(sample,weight,development,temperature,precipitation,diversity,density,devil) %>%
                    mutate(development = factor(development) ) %>%
                    mutate(logseqdepth=read_counts %>% #total log-sequencing depth
                        select(all_of(row.names(StudyDesign))) %>%
                        colSums() %>%
                        log()
                    ) %>%
                    column_to_rownames("sample")

# Genome phylogeny
PData <- genome_tree %>% 
    keep.tip(tip=genomes_to_model)
```

```{r hmsc_formulas_tasmania, warning=FALSE, comments="", message=FALSE}

# Fixed effects formula
XFormula = ~weight + development + diversity + temperature + precipitation + density + devil + logseqdepth

# Study design
rL.animal = HmscRandomLevel(units = levels(StudyDesign$animal))
rL.site = HmscRandomLevel(units = levels(StudyDesign$site))
```

```{r hmsc_models_tasmania, warning=FALSE, comments="", message=FALSE}
#Define model
m = Hmsc(Y=YData,
         XData = XData,
         XFormula = XFormula,
         studyDesign = StudyDesign,
         phyloTree = PData,
         ranLevels = list("animal"=rL.animal, "site"=rL.site),
         distr = "normal",
         YScale = TRUE)

save(m, file = "hmsc/model_tasmania")
```

## In the HPC

```{sh, eval=FALSE}
conda activate hmsc-hpc

model="hmsc/model_tasmania"
init="init/model_tasmania.rds"

export samples=250
export thin=1000
export transient=$(( samples * thin ))
export nChains=4
export verbose=TRUE
export model
export init

# Get initiation object
Rscript hmsc.r $model $init
```

```{sh, eval=FALSE}
cat <<'EOF' > launch_hmsc_model_tasmania.sh
#!/bin/bash
#SBATCH --job-name=hmsc_model_tasmania
#SBATCH --nodes=1
#SBATCH --partition=cpuqueue
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=32gb
#SBATCH --time=150:00:00

# Activate conda environment
source activate hmsc-hpc

# Set output files
output="output/Hmsc_model_tasmania.rds"
mkdir output

# Run model fit
srun python3 -m hmsc.run_gibbs_sampler --input $init --output $output --samples $samples --transient $transient --thin $thin --verbose 100
EOF
```

```{sh, eval=FALSE}
sbatch launch_hmsc_model_tasmania.sh
```